### ISSUE TITLE
Add support to include the ESXi host management IP in the CSR for `SubjectAltName`

### ISSUE THREAD

**Issue by am3rig0** [vmware/powershell-module-for-vmware-cloud-foundation-certificate-management#72]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [x] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [x] Do not leave "+1" or other comments that do not add relevant information or questions.
- [x] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Currently, when generating Certificate Signing Requests (CSRs) for ESXi hosts using the `Request-EsxiCsr` function, there is no support for including the management IP Address of the ESXi host in the Subject Alternative Name (`SubjectAltName`) field of the CSR. 

This request proposes the enhancement of the `Request-EsxiCsr` function to include this, as an optional parameter that can be used. 

### Use Case(s)

- To align the process to be more in line with what is present in SDDC Manager today, which gives hints for Subject Alternative Name creation as part of the certificate generation workflow. 

### Potential Configuration

- `New-VIMachineCertificateSigningRequest` already includes support for SubjectAltName.
- `Get-VMhost` can be used to obtain the IP address of the management VMkernel adapter, in a similar way the value of `$esxiHosts` is retrieved.
- Could include `-IncludeSubjectAltNameIp` parameter in `Request-EsxiCsr` function to make it optional.

### References

[`New-VIMachineCertificateSigningRequest`](https://developer.vmware.com/docs/powercli/latest/vmware.powercli.vcenter/commands/new-vimachinecertificatesigningrequest/#VCenter)

**Comment by bhumitra** [comment]
I reviewed this request - 

New-VIMachineCertificateSigningRequest doesnt include support for using SubjectAltName when it comes to ESXi hosts. 
<img width="714" alt="image" src="https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-certificate-management/assets/8632869/9e7f8149-5028-4ad5-82e0-ad8ed572d13e">
![image](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-certificate-management/assets/8632869/3e6cb64d-69d4-4e49-af30-3937f1f4a656)

Error - 
New-VIMachineCertificateSigningRequest: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.

Because of the limitation of `New-VIMachineCertificateSigningRequest` in PowerCLI, this enhancement cannot be done.
